### ISSUE TITLE
Bad user experience

### ISSUE THREAD

**Issue by Gulshanaggarwal** [NucleoidJS/nucleoid.com#19]
**What's the issue?**
After clicking on learn more button on Homepage it refresh the current page and take away to get started page +also opens a new tab for ID page. I think it's a bad user experience. It may confuse visitor by opening two different pages simultaneously.

**How to regenerate it?**

- Goto - https://nucleoid.com/
- Click the **Learn more button** and observe.

**Comment by Gulshanaggarwal** [comment]
Hey @canmingir  what do you think about it?

**Comment by canmingir** [comment]
Yep, you are right, it is quite annoying. I fixed in 12e1d865351dfbb172d3bf609439dc29f42b03f1

**Comment by Gulshanaggarwal** [comment]
Cool, now It's working as expected. Currently I'm observing Nucleoid.com & will open a request If I find something annoying.
